### ISSUE TITLE
pngjs is probably slow

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/tilelive-gl#32]
pngjs is a pure-JS PNG encoder. It'll probably be much faster to use a native module. This should be benchmarked though.

**Comment by springmeyer** [comment]
@mikemorris want to put together some benchmarks comparing pngjs encoding speeds to the alternatives you are considering?

**Comment by bsudekum** [comment]
I dug a little deeper into what exactly is slow. I benched tilelive-gl and found that png rendering is taking up ~95% of the request time. My setup:

* pool max set 1
* rendering 1 tile at a time
* rendering the same tile ever time
* [Added `console.time`'s here for individual pieces](https://github.com/mapbox/tilelive-gl/blob/bench/index.js#L73-L102)
* [and a `console.time` to compare the overall render time](https://github.com/mapbox/tilelive-gl/blob/bench/test/render.test.js#L45-L47)

Here were the results rendering the same tile ten's of times:
```
acquire: 0ms
render: 14ms
png: 191ms
8-135-87: 205ms
acquire: 0ms
render: 12ms
png: 194ms
8-135-87: 206ms
acquire: 0ms
render: 13ms
png: 195ms
8-135-87: 208ms
acquire: 0ms
render: 13ms
png: 195ms
8-135-87: 208ms
acquire: 0ms
render: 14ms
png: 189ms
8-135-87: 203ms
acquire: 0ms
render: 12ms
png: 190ms
8-135-87: 203ms
```

Notice how much time is spent on the `png` step. It'd be great to get this out of node land and into c++. 

@tmpsantos @springmeyer @mikemorris anyone have time for this?

**Comment by tmpsantos** [comment]
I have some test results to share:

My test consisted on a modified version of [examples/load-from-fs.js](https://github.com/mapbox/node-mapbox-gl-native/blob/master/examples/load-from-fs.js) that would render 1000 maps to the disk in serial (i.e. start a new render cycle only after the previous one has finished). The `FileSource` was fetching the tile/sprite/etc data from my SSD.

I tried a permutation of using native PNG encoding or pngjs, creating a new `Map` or reusing an existing `Map`, reusing the style already set from the previous render cycle or changing the style.

Test | Average time per render cycle (ms)
------------- | -------------
pngjs - reusing `Map` + same style  |  54.71
pngjs - reusing `Map` + new style | 73.95
pngjs - new `Map` + new style  | 130.75
Native encoder - reusing `Map` + same style :zap: | 3.84
Native encoder - reusing `Map` + new style | 58.55
Native encoder - new `Map` + new style  | 114.49

:zap: This is insanely fast but is not exactly a real world scenario because I'm not changing the map to a new position on every new render cycle (so tiles are all cached and wont get reparsed).

My conclusion is that using a native encoder has performance benefits but I don't think pngjs alone is to blame for the high latency. Setting up a new style has a huge performance impact and we must try to reuse a `Map` with a style set when possible.

You can try my branch with the native encoder here:
https://github.com/mapbox/node-mapbox-gl-native/tree/native_png_encoder

And check the full `perf` measurements here:
https://gist.github.com/tmpsantos/20e9333bc3938e8abe2b

Test script example:
https://gist.github.com/tmpsantos/9b0451f153d18f66d2f0

**Comment by tmpsantos** [comment]
@bsudekum I forgot to mention that the "reusing `Map` + same style" is pretty much what you tested and our results are aligned. As you can see, switching to native reduces the rendering time in about ~90%.

Although, the current approach on tilelive-gl seems more like "reusing `Map` + new style" for each request.

**Comment by bsudekum** [comment]
> Setting up a new style has a huge performance impact and we must try to reuse a Map with a style set when possible.

Yep, totally agree. During my testing, ever time tests started, the first map render took 5x longer than any other:

```
acquire: 14ms
render: 912ms  <----
png: 134ms
19-435285-214641: 1061ms
acquire: 0ms
render: 234ms  <----
png: 153ms
3-2-2: 387ms
acquire: 0ms
render: 101ms  <---
png: 141ms
15-16640-11022: 242ms
acquire: 0ms
render: 227ms
```



@tmpsantos I'm going to check out your branch and do some testing myself.

**Comment by kkaefer** [comment]
> Setting up a new style has a huge performance impact and we must try to reuse a Map with a style set when possible.

AFAIK, this is also the way Mapnik-based maps work.

**Comment by bsudekum** [comment]
Just wanted to provide a few numbers with the updated branch @tmpsantos made as a comparison to my benchmark before:

```
acquire: 0ms
render: 102ms
8-135-87: 102ms
acquire: 0ms
render: 105ms
8-135-87: 105ms
acquire: 0ms
render: 109ms
8-135-87: 109ms
acquire: 0ms
render: 107ms
8-135-87: 107ms
acquire: 0ms
render: 103ms
8-135-87: 104ms
acquire: 0ms
render: 106ms
8-135-87: 106ms
acquire: 0ms
render: 102ms
8-135-87: 102ms
acquire: 0ms
render: 112ms
8-135-87: 112ms
```

**Comment by jfirebaugh** [comment]
So all the benchmarks show meaningful performance improvement for native PNG encoder over pngjs in all scenarios. Since that's low hanging fruit, let's implement it first and then look at other bottlenecks.

**Comment by mikemorris** [comment]
FWIW at some point we'll need to add support for JPEG encoding too which is why I had started making this more modular, rather than tied to functions in mbgl core.
